[package]
name = "rust_609"
version = "0.1.0"
authors = ["Dan <dmedani@yelp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.3.4"
bit-vec = "0.6.3"
