[package]
name = "rust_700"
version = "0.1.0"
authors = ["Dan <danmedani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.3.0"
num-traits = "0.2.12"
prime_tools = "0.3.4"
