[package]
name = "euler_250"
version = "0.1.0"
authors = ["Daniel Medani <dmedani@yelp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.1.3"
libmath = "0.1.4"
lru = "0.3.1"