[package]
name = "rust_230"
version = "0.1.0"
authors = ["Dan <danmedani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fast-fibonacci = "0.2.0"
num-bigint = "0.2"
num = "0.2.0"
