[package]
name = "euler_293"
version = "0.1.0"
authors = ["Daniel Medani <dmedani@yelp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6.1"