[package]
name = "euler_234_try2"
version = "0.1.0"
authors = ["Dan Medani <danmedani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.2.2"
