[package]
name = "rust_304"
version = "0.1.0"
authors = ["Dan <danmedani@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.3.4"
fast-fibonacci = "0.1.1"
