[package]
name = "euler_216"
version = "0.1.0"
authors = ["Daniel Medani <dmedani@yelp.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prime_tools = "0.2.2"
libmath = "0.1.4"
num-bigint = "0.2"
num = "0.2.0"
