[package]
name = "euler_193"
version = "0.1.0"
authors = ["dmedani"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.8"
num = "0.2.0"
prime_tools = "0.2.2"
